services:
  api-go:
    build:
      context: .
      args:
        GO_IMAGE: ${GO_IMAGE:-golang:1.25}
    environment:
      - GIN_MODE=release
      - ENV=test
    command: ["make", "test"]
    depends_on:
      - mongo
  mongo:
    image: ${MONGO_IMAGE:-mongo:7.0.32-rc2-jammy}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
