ARG GO_IMAGE=golang:1.25
FROM ${GO_IMAGE}

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV ENV=test

CMD ["go", "test", "-v", "-tags=e2e", "-timeout=120s", "./internal/e2e/..."]
