"""bucket_unique_access_key

Revision ID: d7c9836ae6f5
Revises: 745f027cbef1
Create Date: 2025-03-15 18:10:25.546137

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d7c9836ae6f5"
down_revision: Union[str, None] = "745f027cbef1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_bucket_access_key"), "bucket", ["access_key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bucket_access_key"), table_name="bucket")
    # ### end Alembic commands ###
