"""bucket_unique_access_key

Revision ID: 2dc946c0023c
Revises: 745f027cbef1
Create Date: 2025-03-15 17:52:44.917825

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2dc946c0023c"
down_revision: Union[str, None] = "745f027cbef1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "bucket", ["access_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bucket", type_="unique")
    # ### end Alembic commands ###
