services:
  s3aas-postgres-dc:
    image: postgres:16
    container_name: s3aas-postgres-dc-local
    restart: always
    expose:
      - 5432
    ports:
      - 5555:5432
    env_file: 'local.env'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - s3aas_net

networks:
  s3aas_net:
    driver: bridge
