services:
  sfree-postgres-dc:
    image: postgres:16
    container_name: sfree-postgres-dc-local
    restart: always
    expose:
      - 5432
    ports:
      - 5555:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - sfree_net

networks:
  sfree_net:
    driver: bridge
